### ISSUE TITLE
instrumentation

### ISSUE THREAD

**Issue by nicolasochem** [flashbake/prototype#21]
The public goods relay will have a webpage displaying:

* number of transactions succesfully submitted on-chain
* number of observed flashbakers so far
* time before next flashbake block

Instrument the relay to display some of this info. This would be a prometheus endpoint, and there would be no persistence. The collection side will handle persistence.

**Comment by innov8r** [comment]
Metrics exposed in Prometheus exposition format for collection on the relay endpoint's /metrics URL path:
* flashbake_successful_bundles_total: total number of transactions successfully submitted on-chain (counter)
* flashbake_successful_bakers_total: number of unique flashbakers responsible for above transactions (counter)
* flashbake_pending_bundles: current number of transactions in relay queue (gauge)
* flashbake_dropped_bundles: total number of dropped transactions, currently not used (counter)
* flashbake_block_wait_seconds: seconds before next flashbake block at last bundle's relay time (gauge)

https://github.com/flashbake/endpoints-monorepo/commit/17136f599b5cc27aa1c496a2e7dc27dd0b06a39e

**Comment by nicolasochem** [comment]
Looks good:

```
<<K9s-Shell>> Pod: flashbake/regular-baker-0 | Container: octez-node 
~ $ curl http://flashbake-relay:10732/metrics
# HELP flashbake_received_bundles_total Total number of bundles received by the relay
# TYPE flashbake_received_bundles_total counter
flashbake_received_bundles_total 1

# HELP flashbake_successful_bundles_total Total number of bundles successfully submitted on-chain
# TYPE flashbake_successful_bundles_total counter
flashbake_successful_bundles_total 1

# HELP flashbake_successful_bakers_total Number of unique flashbakers with bundles on-chain
# TYPE flashbake_successful_bakers_total counter
flashbake_successful_bakers_total 1

# HELP flashbake_pending_bundles Current number of bundles in relay queue
# TYPE flashbake_pending_bundles gauge
flashbake_pending_bundles 0

# HELP flashbake_bundle_resends_total Total number of dropped bundles
# TYPE flashbake_bundle_resends_total counter
flashbake_bundle_resends_total 1

# HELP flashbake_dropped_bundles Total number of dropped bundles
# TYPE flashbake_dropped_bundles counter
flashbake_dropped_bundles 0

# HELP flashbake_block_wait_seconds Expected duration until the next Flashbake block for the most recent submitted or resent bundle at the time of its relay
# TYPE flashbake_block_wait_seconds gauge
flashbake_block_wait_seconds 2.815
~ $ 
```
